### ISSUE TITLE
Version 2.2.0 broke html-minifier-terser integration

### ISSUE THREAD

**Issue by jceb** [PlayForm/Compress#214]
Since version 2.2.0 I can't pass `removeAttributeQuotes: false` to the HTML minifier anymore like this:

```js
    compress({
      HTML: {
        removeAttributeQuotes: false,
      },
    }),
```

The issue that triggered my investigation was broken open graph data - service like Twitter wouldn't display my images anymore. Missing attribute quotes were the reason for the issue. I'd therefore also recommend to change the default of astro-compress to not remove attribute quotes anymore.

**Comment by NikolaRHristov** [comment]
Hi, thank you for this!

Starting [`v2.2.0`](https://github.com/astro-community/AstroCompress/releases/tag/v2.2.0) the option types have been changed to allow for multiple parsers / compressors.

The new option layout is now: 

```ts
/**
 * @module Option
 *
 */
export default interface Type extends Option {
	/**
	 * csso, lightningcss option properties
	 *
	 */
	CSS?:
		| boolean
		| {
				csso?: csso;
				lightningcss?: lightningcss;
		  };

	/**
	 * html-minifier-terser option properties
	 *
	 */
	HTML?:
		| boolean
		| {
				"html-minifier-terser"?: html_minifier_terser;
		  };

	/**
	 * sharp option properties
	 *
	 */
	Image?:
		| boolean
		| {
				"sharp"?: sharp;
		  };

	/**
	 * terser option properties
	 *
	 */
	JavaScript?:
		| boolean
		| {
				"terser"?: terser;
		  };

	/**
	 * svgo option properties
	 *
	 */
	SVG?:
		| boolean
		| {
				"svgo"?: svgo;
		  };

	/**
	 * Map to different file paths
	 *
	 */
	Map?: boolean | _Map;

	/**
	 * Parsers for different file types
	 *
	 */
	Parser?: Parser;
}

import type html_minifier_terser from "../Type/HTML/html-minifier-terser.js";
import type terser from "../Type/JavaScript/terser.js";
import type svgo from "../Type/SVG/svgo.js";
import type csso from "./CSS/csso.js";
import type lightningcss from "./CSS/lightningcss.js";
import type sharp from "./Image/sharp.js";

import type _Map from "./Map.js";
import type Parser from "./Parser.js";

import type Option from "files-pipe/Target/Interface/Option.js";
```

since [`v2.2.2`](https://github.com/astro-community/AstroCompress/releases/tag/v2.2.2) as per: https://github.com/astro-community/AstroCompress/blob/main/Source/Interface/Option.ts

To fix your issue try:

```ts
compress({
	HTML: {
		"html-minifier-terser": {
			removeAttributeQuotes: false,
		},
	},
}),
```

I would recommend installing a modern editor with autocomplete for TypeScript types such as the VSCode editor, so you can see the suggestions and errors before they happen.

![image](https://github.com/astro-community/AstroCompress/assets/90222871/4ff459cc-f0b2-4ed8-908b-48cc429f5dc7)

![image](https://github.com/astro-community/AstroCompress/assets/90222871/b53d086c-61de-408e-87d9-df53be1296e7)

Also installing `@astrojs/check` and turning on `astro check` before your build process so that errors are shown in the console if you're using a CI

![image](https://github.com/astro-community/AstroCompress/assets/90222871/df4e017e-0c6c-4985-94f0-de720783dcea)

**Comment by NikolaRHristov** [comment]
Apologies for not announcing breaking changes.

**Comment by NikolaRHristov** [comment]
Version `v2.2.4` will allow for backwards compatibility and proper in-flow of options, meaning you can still pass 

```ts
compress({ HTML: { removeAttributeQuotes: false, });
```

and have it flow properly to the `html-minifier-terser` minifier.

**Comment by bennycode** [comment]
@NikolaRHristov where can I find v2.2.4? The `latest` tag on npm points to v2.2.3: https://www.npmjs.com/package/astro-compress/v/latest

With v2.2.3 the typings want me to define the HTML properties like this:

```ts
compress({
  HTML: {
    'html-minifier-terser': {
      removeAttributeQuotes: true,
    }
  }
})
```

**Comment by NikolaRHristov** [comment]
Version `v2.2.4` is not released yet. Expect it later today.
